name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  test-linux:
    name: Test Linux
    runs-on: [ubuntu-latest]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test all modules
        run: go test ./api/krusty -v -run TestRemoteResourceSsh
        env:
          KUSTOMIZE_DOCKER_E2E: true
